import Head from "next/head";
import { Layout } from "../layouts";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title="Home Page">
        <h1>hola</h1>
      </Layout>
      <footer></footer>
    </div>
  );
}
