import Head from "next/head";
import { useState } from "react";
import { Layout } from "../layouts";
import { useZxing } from "react-zxing";

export default function Home() {
  const [result, setResult] = useState("No result");
  const { ref } = useZxing({
    onResult(result) {
      setResult(result.getText());
    },
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title="Home Page">
        <video ref={ref} />
        <p>
          <span>Last result:</span>
          <span>{result}</span>
        </p>
      </Layout>
      <footer></footer>
    </div>
  );
}
